### PR TITLE
feat/automated-code-analysis-workflow-MD

### LINKED ISSUE #5: Add automated code scanning workflow
Setup a CodeQL Analysis workflow to automatically detect common vulnerabilities and coding errors for JavaScript when a pull request is merged or a commit is made to the main branch.

Before contributing, make sure you follow the guidelines in [Contributions.md](https://github.com/KushGabani/radiokey/blob/main/Contributions.md)
Thanks! **Happy Contributions** ✨

### PR DESCRIPTION
**Pull request by ManavD522**
- [x] Followed the proper guidelines above
- [x] Provided comments to necessary parts of the code
- [x] Properly formatted the code using prettier
- [x] Tested the bot locally and it works fine

closes #5

### CODE REVIEW

**Comment by KushGabani** [comment]
Hey! Thanks for your contribution. Just one last thing have you tested your code locally?

**Comment by ManavD522** [comment]
I've just added the automated workflow so i don't think it's feasible to test the code locally. Maybe you can accept the two file .yml files for now and make an empty commit to see if the workflow has been set up

**Comment by KushGabani** [comment]
Congratulations and Thank you for your first contribution!! Since you have followed the guidelines as stated in Contributions.md, I'll soon add you to the list of contributors

**Comment by KushGabani** [comment]
I have successfully tested two automated code analysis workflows and it works just fine. Thank you! Hope you become an active participant of this repository.

**Pull request merged**
